# Generated by Django 6.0.1 on 2026-08-13 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('daily_generations_left', models.IntegerField(default=3)),
                ('last_generation_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
                ('template_id', models.IntegerField(default=1)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resume.user')),
            ],
        ),
    ]
