# Generated by Django 6.0.1 on 2026-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
