# Generated by Django 6.0.1 on 2026-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_id',
            field=models.IntegerField(default=1),
        ),
    ]
