# Generated by Django 6.0.1 on 2026-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
